### ISSUE TITLE
LinearInterpolation Errors when interpolating `Vector{Array}`

### ISSUE THREAD

**Issue by dafred94** [SciML/DataInterpolations.jl#116]
```
t = Float64[0, 1, 2]
y = [i*ones(2) for i in 0:2]
interp = LinearInterpolation(y, t)

interp(1.0) # errors
interp(1.001) # works
```

The error that I see is:
`ERROR: MethodError: no method matching isnan(::Vector{Float64})`

It seems like the argument to `interp` may not be equal to any entry in `t`.

**Comment by ChrisRackauckas** [comment]
@GlenHertz this might've been introduced by your change?
