### ISSUE TITLE
Dead link in tutorial for Quadratic and Cubic Spline

### ISSUE THREAD

**Issue by ElisabethRoesch** [SciML/DataInterpolations.jl#141]
Under Quadratic and Cubic Spline in [this file](https://github.com/PumasAI/DataInterpolations.jl/blob/master/example/DataInterpolations.jmd) , there are two dead links to https://www.math.uh.edu/~jingqiu/math4364/spline.pdf.

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas, can we close this as the links mentioned have been removed?
