### ISSUE TITLE
Extrapolations

### ISSUE THREAD

**Issue by KronosTheLate** [SciML/DataInterpolations.jl#163]
Will this library support extrapolations at some point? I generally want to buy in to SciML and related packages, but need extrapolating capabilities.

**Comment by ChrisRackauckas** [comment]
I think it would be fine to have a switch to allow them to extrapolate.

**Comment by alecloudenback** [comment]
@KronosTheLate FYI I am looking for extrapolations too and found this: https://jipolanco.github.io/BSplineKit.jl/stable/generated/interpolation/#extrapolation-example

**Comment by KronosTheLate** [comment]
Thanks for the helpfullness. I however just ended up using "Interpolations.jl", which provides extrapolation, so I have a solution that works for me ^_^

**Comment by ChrisRackauckas** [comment]
All extrapolations were handled in https://github.com/SciML/DataInterpolations.jl/pull/184 with a switch in https://github.com/SciML/DataInterpolations.jl/pull/193
