### ISSUE TITLE
Better show methods 

### ISSUE THREAD

**Issue by DanielVandH** [SciML/DataInterpolations.jl#167]
Currently, the `show` method for the interpolants concatenates the vectors (i.e. shows `vcat(u, t)`):

```julia
julia> u = rand(5);

julia> t = 0:4;

julia> LinearInterpolation(u, t)
10-element LinearInterpolation{Vector{Float64}, UnitRange{Int64}, true, Float64}:
 0.5483587984330037
 0.26039471258152735
 0.19683677241504127
 0.7099479665944533
 0.08217814764401155
 0
 1
 2
 3
 4
```

which is a consequence of having `AbstractInterpolant <: AbstractVector`. I wonder if it would be cleaner to overwrite this, showing e.g. `hcat(u, t)` instead? e.g.

```julia
julia> function Base.show(io::IO, mime::MIME"text/plain", F::DataInterpolations.AbstractInterpolation)
           Base.show(io, mime, hcat(F.u, F.t))
       end

julia> interp
5×2 Matrix{Float64}:
 0.0589206  0.0
 0.115624   1.0
 0.862211   2.0
 0.330109   3.0
 0.430882   4.0
```

(or whatever is the best way for defining a new `show` like this to also include `10-element LinearInterpolation{Vector{Float64}, UnitRange{Int64}, true, Float64}:`).

**Comment by ChrisRackauckas** [comment]
We should probably customize it even a bit more, just to say "LinearInterpolation with 10 points at time points: [...]`
