### ISSUE TITLE
Support for `SymbolicUtils.BasicSymbolic{Real}`

### ISSUE THREAD

**Issue by bradcarman** [SciML/DataInterpolations.jl#168]
I'm attempting to use DataInterpolations with a ModelingToolkitStandardLibrary.Blocks.TimeVaryingFunction in ModelingToolkit.  When I run `structural_simplify` it seems the derivative is needed.  I supply this as

```julia
f = LinearInterpolation(x, time)
Symbolics.derivative(::typeof(f), args::NTuple{1, Any}, ::Val{1}) = DataInterpolations.derivative(f, args[1])

@named system = System(false, f)
sys = structural_simplify(system) 
```

However this gives:  ERROR: MethodError: no method matching derivative(::LinearInterpolation{Vector{Float64}, Vector{Float64}, true, Float64}, ::SymbolicUtils.BasicSymbolic{Real}, ::Int64)

I also get this error if I simply run 

```julia
julia> f(Symbolics.unwrap(t))
ERROR: MethodError: no method matching (::LinearInterpolation{Vector{Float64}, Vector{Float64}, true, Float64})(::SymbolicUtils.BasicSymbolic{Real})
```

Seems DataInterpolations is not supporting some latest Symbolics features?

**Comment by ChrisRackauckas** [comment]
Handled.
