### ISSUE TITLE
Few methods don't extrapolate, derivatives, integrals not implemented

### ISSUE THREAD

**Issue by sathvikbhagavan** [SciML/DataInterpolations.jl#175]
This issue lists the methods for which extrapolation, derivatives, derivatives extrapolation, integrals error out/not implemented:

Extrapolation does not work in:

- [x] BSplineInterpolation
- [x] BSplineApprox

Derivative extrpolation does not work in:

- [x]  LinearInterpolation
- [x]  QuadraticSpline
- [x]  CubicSpline
- [x]  BSplineInterpolation
- [x]  BSplineApprox

Derivatives not implemented:

- [x]  RegularizationSmooth
- [x]  Curvefit

Integrals not implemented:

- [ ] AkimaInterpolation
- [ ]  LagrangeInterpolation
- [ ]  BSplineInterpolation
- [ ]  BSplineApprox
- [ ]  RegularizationSmooth
- [ ] Curvefit

**Comment by ChrisRackauckas** [comment]
What's left here? Can you convert it to check boxes?

**Comment by sathvikbhagavan** [comment]
The things left are derivatives for RegularizationSmooth, Curvefit and integrals for a few methods

**Comment by sathvikbhagavan** [comment]
@ChrisRackauckas, I was looking into implementing integral for LagrangeInterpolation. I was thinking of two ways:
1. Numerically Integrate each of the basis polynomial using QuadGK and do a weighted sum with the data points
2. Directly numerically integrate the interpolating function. 

I think (1) might be better than (2), wanted to clarify that. 
I was also trying to look for a different way where we have some analytical expression of the integral to evaluate but I couldn't find anything. Do you know any way along these lines?

**Comment by ChrisRackauckas** [comment]
If it's resorting to a numerical integration it might be better to just error and say that no analytical solution is given here.
