### ISSUE TITLE
Boundary condition of Cubic Spline interpolation

### ISSUE THREAD

**Issue by KalvinMa** [SciML/DataInterpolations.jl#234]
Hi,
May I ask what boundary condition are used in cubic spline interpolation function? I compared the interpolation results with SciPy and found the result is different with all cases with different boundary conditions in SciPy. It approaches the "natural" one, but still a little bit different.  Thanks a lot.
![image](https://github.com/SciML/DataInterpolations.jl/assets/27984859/37b2df8b-a55c-43ed-b78b-a6ab4295e1ed)

**Comment by sathvikbhagavan** [comment]
Are you referring to extrapolation? It extrapolates the last cubic polynomial on both sides.

**Comment by KalvinMa** [comment]
I don't think I use the extrapolation, here is the code.
**In Julia:**
```
# Cubic Spline for TBP curve
T = [310.217183796031 ,
341.254055958343 ,
369.798567124936 ,
387.403465409701 ,
406.403097762664 ,
433.370431885499 ,
480.578081202443 ,
]
V = [0.0, 10.0, 30.0, 50.0, 70.0, 90.0, 100.0]
CubicS = CubicSpline(T, V)
v = range(2.5, 100.0, step=5.0)
CubicS.(v)
```

**In SciPy:**
```
import numpy as np
from scipy.interpolate import CubicSpline
import matplotlib.pyplot as plt
T = [310.217183796031 ,
341.254055958343 ,
369.798567124936 ,
387.403465409701 ,
406.403097762664 ,
433.370431885499 ,
480.578081202443 ,
]
V = [0.0, 10.0, 30.0, 50.0, 70.0, 90.0, 100.0]
cs_natural = CubicSpline(Vols, TBPs, bc_type='natural')
cs_knot = CubicSpline(Vols, TBPs, bc_type='not-a-knot')
cs_clamped = CubicSpline(Vols, TBPs, bc_type='clamped')
v = np.array(range(25, 1000, 50)) / 10.0
cs_natural(v)
cs_knot(v)
cs_clamped(v)
```
