### ISSUE TITLE
PCHIP implementation

### ISSUE THREAD

**Issue by jer-j** [SciML/DataInterpolations.jl#283]
**What kind of problems is it mostly used for? Please describe.**

This algorithm can be used for any types of problems where preserving monotonicity is important, particularly useful for creating geometry.

**Describe the algorithm you’d like**

The PCHIP algorithm (piecewise cubic Hermite interpolating polynomial) I am referring to is a type of `CubicHermiteSpline` that was recently added #280. However, the derivatives are specified in a particular way [1]:

given:
![image](https://github.com/SciML/DataInterpolations.jl/assets/122048724/cd7c801e-3fef-45ac-b4c1-5c0daa418888)

then if $x_k$ is a local min or max (i.e. $\delta_k$ and $\delta_{k+1}$ have different signs)

$$d_k = 0$$

else we use a weighted harmonic mean 
$$\frac{w_1+w_2}{d_k}=\frac{w_1}{\delta_{k-1}}+\frac{w_2}{\delta_k},$$
where
$$w_1=2 h_k+h_{k-1}, w_2=h_k+2 h_{k-1} .$$

**Other implementations to know about**
[SciPy's `PchipInterpolator`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PchipInterpolator.html)
[MATLAB's `pchip`](https://www.mathworks.com/help/matlab/ref/pchip.html)
[`PCHIPInterpolation.jl`](https://github.com/gerlero/PCHIPInterpolation.jl)

**References**

[1] [Mathworks paper](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/moler/interp.pdf), see sections 3.4 and 3.6
[2] [F. N. Fritsch and R. E. Carlson, Monotone Piecewise Cubic Interpolation, SIAM Journal on Numerical Analysis, 17 (1980), pp. 238-246.](https://www.jstor.org/stable/2156610)
[3] [Kahaner, David, Cleve Moler, Stephen Nash. Numerical Methods and Software. Upper Saddle River, NJ: Prentice Hall (1988), pp. 100-106.](https://www.hlevkin.com/hlevkin/60numalgs/Fortran/Kahaner-Moler-Numerical-Methods-and-Software.pdf#page=112)

I'm happy to implement this in my own PR but was curious on feedback for implementation. Namely, should this be implemented as a subtype of `CubicHermiteSpline`? I'm not certain because the way the [1] describes how to evaluate the interpolant is different than `CubicHermiteSpline` is evaluated.

**Comment by SouthEndMusic** [comment]
If I understand correctly, you can use the existing `CubicHermiteSpline` under the hood, when you define a function

```julia
function PCHIP(u, t; extrapolate = true)
   du = pchip_du(u, t)
   CubicHermiteSpline(du, u, t; extrapolate)
end
```

and the function `pchip_du` which computes the derivatives from the input data.

**Comment by SouthEndMusic** [comment]
I'm pretty sure my implementation does the same as what is described in section 3.3 of [1], be it in an optimized way

**Comment by jer-j** [comment]
I'm not so sure. If I try to check by making the terms look similar to [1] 3.6:

You construct the interpolating polynomial as follows (where k is the interval index):

$$P(t) = u_k + \Delta t_0 d_k + \Delta t_0^2 c_{1k} + \Delta t_0^2 \Delta t_1 c_{2k}$$
where

$$\Delta t_0 = t - t_k = s$$

$$\Delta t_1 = t - t_{k+1}$$

$$ c_1 = \frac{u_{k+1} -u_k - d_k (t_{k+1} - t_k)}{(t_{k+1} - t_k)^2} = \frac{\delta_k - d_k}{h}$$

$$c_2 = \frac{d_{k+1} - d_k - 2c_1 (t_{k+1} - t_k)}{(t_{k+1} - t_k)^2} = \frac{d_{k+1} - 2\delta_k - 3d_k}{h^2}$$

Which, in formal terms, reduces to
$$P(x) = y_k + s d_k + s^2 \frac{\delta_k - d_k}{h} + s^2 (x-x_{k+1})\frac{d_{k+1} - 2\delta_k - 3d_k}{h^2}$$

where $x=t,y=u$
$$h = h_k = x_{k+1} - x_k$$

$$\delta_k = \frac{y_{k+1} - y_k}{h_k}$$

$$d_k = P'(x_k)$$

which is not the same in the quadratic and cubic terms as

$$P(x) = y_k + s d_k + s^2 \frac{3\delta_k - 2d_k - d_{k+1}}{h} + s^3\frac{d_k - 2\delta_k + d_{k+1}}{h^2}$$

which is valid for all kinds of piecewise cubic Hermite interpolation

Full disclosure, I am not a mathematician. So, I checked to see if I had made a mistake, and your suggestion worked. Unfortunately:
![plot_5](https://github.com/SciML/DataInterpolations.jl/assets/122048724/ee1b3df0-701d-47f4-8cf7-704836d73b5f)

<details>
<summary>Code</summary>

```julia
using PCHIPInterpolation, Plots

xs = [-2.0, -1, 0, 1, 2]
ys = [1.0, 0, 0, 0, 1]

itp_pchip = Interpolator(xs, ys; extrapolate = true)

import DataInterpolations: CubicHermiteSpline

function PCHIP(u, t; extrapolate = true)
    du = PCHIPInterpolation._pchip_ds_scipy(u, t)
    CubicHermiteSpline(du, u, t; extrapolate)
end

itp_sciml = PCHIP(xs, ys; extrapolate = true)

x = -4:0.1:4;
plt = scatter(xs, ys, label = "input data")
plot!(plt, x, itp_pchip.(x), label = "PCHIPInterpolation.jl")
plot!(plt, x, itp_sciml(x), label = "DataInterpolations.jl", legend = :bottomright)
```

</details> 

The expected output is something like this:
![plot_12](https://github.com/SciML/DataInterpolations.jl/assets/122048724/c45652cd-339e-4165-8ca2-eadf6bfaab4e)

**Comment by SouthEndMusic** [comment]
I knew something was fishy when your SciML interpolation did not even go trough the data points. A subtlety of `DataInterpolations` you missed is that the constructor first expects the `ys` and then the `xs`. Adapting your example:

```julia
using DataInterpolations, PCHIPInterpolation
using Plots

xs = [-2.0, -1.0, 0.0, 1.0, 2.0]
ys = [1.0, 0.0, 0.0, 0.0, 1.0]

function PCHIP(u, t; extrapolate = true)
    du = PCHIPInterpolation._pchip_ds_scipy(t, u)
    @show du
    CubicHermiteSpline(du, u, t; extrapolate)
end

itp_sciml = PCHIP(ys, xs; extrapolate = true)
scatter(xs, ys)
plot!(itp_sciml)
```
![figure](https://github.com/SciML/DataInterpolations.jl/assets/74617371/a39f0397-07c4-44d3-8635-df3ab939b63d)

**Comment by SouthEndMusic** [comment]
It looks like you made a sign mistake in translating $c_2$, which actually gives

$$
c_2 = \frac{d_k  - 2\delta_k + d_{k+1}}{h^2}.
$$

Also note that

$$
x - x_{k+1} = (x - x_k) - (x_{k+1} - x_k) = s - h_k.
$$

And so 

$$
\begin{align}
P(x) &=& u_k + \Delta t_0 d_k + \Delta t_0^2 c_1 + \Delta t_0^2\Delta t_1 c_2 \\
&=& y_k +sd_k + s^2 c_1 + s^2(s - h) c_2 \\
&=& y_k +sd_k + s^2 \frac{\delta_k - d_k}{h} + s^2(s - h) \frac{d_k  - 2\delta_k + d_{k+1}}{h^2} \\
&=& y_k +sd_k + s^2 \frac{\delta_k - d_k - (d_k  - 2\delta_k + d_{k+1})}{h} + s^3\frac{d_k  - 2\delta_k + d_{k+1}}{h^2} \\
&=& y_k +sd_k + s^2 \frac{3\delta_k - 2d_k - d_{k+1}}{h} + s^3\frac{d_k  - 2\delta_k + d_{k+1}}{h^2}
\end{align}
$$

**Comment by jer-j** [comment]
Ahhh, thank you for catching my mistake! So using `CubicHermiteSpline` is possible to create a pchip interpolation.

**Comment by SouthEndMusic** [comment]
I still think it would be nice to add it in, even though it's a quite simple wapper of `CubicHermiteSpline`. You probably want to write your own code for computing the `du` so you don't have to add a new dependency
