### ISSUE TITLE
Constraining range of interpolation

### ISSUE THREAD

**Issue by astro-kevin** [SciML/DataInterpolations.jl#292]
Is there a way to constrain the range of the interpolation? e.g. I want to make an `AkimaInterpolation` but I want the outputs to only be positive?

**Comment by SouthEndMusic** [comment]
If you don't care about derivatives:

```julia
A = AkimaInterpolation(u, t)
eval_A(t_) = clamp(A(t_), lo, hi)
```

**Comment by astro-kevin** [comment]
Is there an implementation which works with derivatives?

**Comment by SouthEndMusic** [comment]
Let's be precise about the problem: In what way do you want the interpolation to be differentiable? In the mathematical sense, or do you want to use `DataInterpolations.derivative` or a specific AD package? Some more information about your use case might help here.

There is no efficient way in `DataInterpolations` to obtain the range of an interpolation, although some interpolation types have nice properties in this regard.

**Comment by astro-kevin** [comment]
I'd like to use `ForwardDiff` to differentiate it. My use-case is that I have a time varying quantity which I know never goes below 0, but due to how interpolation works, it throws some values into the negatives when the rate of change is big, so I'm looking for a way to somehow force it to always interpolate >0. I'm using AkimaInterpolation at the moment, but I'm open to switching to another spline method.

**Comment by SouthEndMusic** [comment]
It sounds like you want interpolation with local convexity properties so that the interpolation does not overshoot the data. I don't know from the top of my head which methods have this property.

**Comment by SouthEndMusic** [comment]
@astro-kevin can you also give an example?

**Comment by SouthEndMusic** [comment]
I think PCHIP interpolation might be a good candidate for you, as it is guaranteed not to overshoot. It is not done yet, it was suggested here: https://github.com/SciML/DataInterpolations.jl/issues/283

**Comment by astro-kevin** [comment]
> @astro-kevin can you also give an example?

Here you go:
x values
`[6.791390744557552e8, 7.070120692276629e8, 7.357080095340183e8, 7.650547154724817e8, 7.953377732904905e8, 8.262892758848644e8, 8.581056913126638e8, 8.907024681774093e8, 9.240880453929646e8, 9.582710918790629e8, 9.933604622496704e8, 1.0292664997565169e9, 1.0659972153375142e9, 1.1036653581333e9, 1.1421769036507227e9, 1.1815402286848478e9, 1.2218708563315039e9, 1.2630712844898963e9, 1.3051492865673156e9, 1.3482235382047653e9, 1.392193054974913e9, 1.4371785756406274e9, 1.483076055835938e9, 1.5300085878965065e9, 1.577753180029025e9, 1.6266666941311235e9, 1.67652468498346e9, 1.7273338946409273e9, 1.7793429703532004e9, 1.832197841268106e9, 1.8862716833809853e9, 1.941203362409068e9, 1.9973719124117074e9, 2.0545358728689203e9, 2.1128282306452894e9, 2.172257374393114e9, 2.232701288775207e9, 2.2944260629433947e9, 2.3571786931112576e9, 2.4210956101005635e9, 2.486183963119266e9, 2.552450182964812e9, 2.619900360140457e9, 2.6885398233809443e9, 2.7583743481169596e9, 2.8294089289359417e9, 2.9016477520188007e9, 2.9752368116074886e9, 3.050040012590594e9, 3.1262043907104836e9, 3.203590976156871e9, 3.2822025766905494e9, 3.362187185824641e9, 3.4435480641066747e9, 3.526142206529048e9, 3.610117379714123e9, 3.69547685841344e9, 3.782221971308321e9, 3.8703542985865817e9, 3.960025499246157e9, 4.0509329159676304e9, 4.1433801455385375e9, 4.2372134827372823e9, 4.332585745245504e9, 4.42949557800905e9, 4.527785588847821e9, 4.6276079215446825e9, 4.728959151607614e9, 4.831992579775848e9, 4.936388371718357e9, 5.042615972359425e9, 5.150351540426328e9, 5.259587906300355e9, 5.370637893543748e9, 5.483332574250255e9, 5.597499874197149e9, 5.713616678824965e9, 5.831346213258126e9, 5.950839544722556e9, 6.072083592751027e9, 6.195228369734235e9, 6.320094512101202e9, 6.4468300027655115e9, 6.57525118304769e9, 6.705670315341376e9, 6.838067740318667e9, 6.972421225110228e9, 7.1085430555991955e9, 7.246738559162813e9, 7.387151092833175e9, 7.529418333374686e9, 7.67367922760088e9, 7.820068139296936e9, 7.9687175061451025e9, 8.119428933534547e9, 8.272495645168805e9, 8.42754891778001e9, 8.585044839050801e9, 8.744774067776436e9, 8.907022198767035e9, 9.071411202306694e9, 9.238383393765379e9, 9.407723464781567e9, 9.57953881837197e9, 9.75409646093819e9, 9.931008306812086e9, 1.0110696445607868e10, 1.0293092516779022e10, 1.0478283115615255e10, 1.0666035004716991e10, 1.0856905143484087e10, 1.1050491978401829e10, 1.1247181325785295e10, 1.1446879325484026e10, 1.1649489873032072e10, 1.1855532096420149e10, 1.2064586801248566e10, 1.2277154396736849e10, 1.2492963249786226e10, 1.2712190677773657e10, 1.2935005054798855e10, 1.3161415803527374e10, 1.3391571393923643e10, 1.3625464261400404e10, 1.3863368101695465e10]`
y values
`[1.714705792e9, 1.677940992e9, 2.932352768e9, 3.448529152e9, 3.717647104e9, 3.904411904e9, 4.360293888e9, 4.81617664e9, 5.350000128e9, 5.597059072e9, 5.975000064e9, 6.21617664e9, 6.4264704e9, 6.444117504e9, 6.558823936e9, 6.502941184e9, 8.319117312e9, 9.12205824e9, 9.923529728e9, 1.0770588672e10, 1.2089705472e10, 1.2567646208e10, 1.2067647488e10, 1.3304411136e10, 1.4051470336e10, 1.341764608e10, 1.341617664e10, 1.5676470272e10, 1.7397057536e10, 1.8176468992e10, 1.9911763968e10, 2.0999999488e10, 2.15735296e10, 2.4176470016e10, 2.3955881984e10, 2.6705883136e10, 2.5382350848e10, 2.3897059328e10, 2.6720587776e10, 2.5397057536e10, 2.5176469504e10, 2.5661765632e10, 2.4911765504e10, 2.5191176192e10, 2.5014706176e10, 2.5073528832e10, 2.7352940544e10, 2.923529216e10, 2.7191175168e10, 2.7617646592e10, 2.9132353536e10, 3.0161762304e10, 2.9147056128e10, 2.897058816e10, 3.080882176e10, 3.1235295232e10, 2.9764704256e10, 3.2161763328e10, 3.2926470144e10, 3.3500000256e10, 3.3941174272e10, 3.405882368e10, 3.516176384e10, 3.661764608e10, 3.5941175296e10, 3.6352937984e10, 3.6500000768e10, 3.611764736e10, 3.6838232064e10, 3.854411776e10, 3.9132352512e10, 4.2573529088e10, 4.3720589312e10, 5.1897061376e10, 5.86911744e10, 6.4147058688e10, 7.3000001536e10, 8.6573531136e10, 1.3483823104e11, 1.49852946432e11, 1.551470592e11, 1.6588234752e11, 1.69264709632e11, 1.6882352128e11, 1.75882338304e11, 1.8235293696e11, 1.84999985152e11, 1.87794112512e11, 1.25470588928e11, 6.3161765888e10, 8.39558784e8, 1.73088227328e11, 1.61617641472e11, 1.62500001792e11, 1.55294121984e11, 1.502941184e11, 1.51176462336e11, 1.51029415936e11, 1.49999992832e11, 1.54999996416e11, 1.56470575104e11, 1.5720587264e11, 1.63676471296e11, 1.62352939008e11, 1.64264706048e11, 1.64264706048e11, 1.71176460288e11, 1.7852940288e11, 1.79999997952e11, 1.85588219904e11, 1.88382347264e11, 1.87794112512e11, 1.90882349056e11, 1.86029408256e11, 1.95147055104e11, 1.97352931328e11, 1.988235264e11, 1.97499994112e11, 1.939705856e11, 1.88529410048e11, 1.85147047936e11, 1.89558816768e11, 1.89852925952e11, 1.9294117888e11, 1.91617646592e11]`

Notice how there's a sharp dip, and the interpolation makes it go negative. I don't really care if it overshoots the value of the data, but I really would rather it didn't go to an impossible value (-ve).

**Comment by SouthEndMusic** [comment]
As a human I can parse figures better (: 

```julia
using DataInterpolations
using Plots

u = [1.714705792e9, 1.677940992e9, 2.932352768e9, 3.448529152e9, 3.717647104e9, 3.904411904e9, 4.360293888e9, 4.81617664e9, 5.350000128e9, 5.597059072e9, 5.975000064e9, 6.21617664e9, 6.4264704e9, 6.444117504e9, 6.558823936e9, 6.502941184e9, 8.319117312e9, 9.12205824e9, 9.923529728e9, 1.0770588672e10, 1.2089705472e10, 1.2567646208e10, 1.2067647488e10, 1.3304411136e10, 1.4051470336e10, 1.341764608e10, 1.341617664e10, 1.5676470272e10, 1.7397057536e10, 1.8176468992e10, 1.9911763968e10, 2.0999999488e10, 2.15735296e10, 2.4176470016e10, 2.3955881984e10, 2.6705883136e10, 2.5382350848e10, 2.3897059328e10, 2.6720587776e10, 2.5397057536e10, 2.5176469504e10, 2.5661765632e10, 2.4911765504e10, 2.5191176192e10, 2.5014706176e10, 2.5073528832e10, 2.7352940544e10, 2.923529216e10, 2.7191175168e10, 2.7617646592e10, 2.9132353536e10, 3.0161762304e10, 2.9147056128e10, 2.897058816e10, 3.080882176e10, 3.1235295232e10, 2.9764704256e10, 3.2161763328e10, 3.2926470144e10, 3.3500000256e10, 3.3941174272e10, 3.405882368e10, 3.516176384e10, 3.661764608e10, 3.5941175296e10, 3.6352937984e10, 3.6500000768e10, 3.611764736e10, 3.6838232064e10, 3.854411776e10, 3.9132352512e10, 4.2573529088e10, 4.3720589312e10, 5.1897061376e10, 5.86911744e10, 6.4147058688e10, 7.3000001536e10, 8.6573531136e10, 1.3483823104e11, 1.49852946432e11, 1.551470592e11, 1.6588234752e11, 1.69264709632e11, 1.6882352128e11, 1.75882338304e11, 1.8235293696e11, 1.84999985152e11, 1.87794112512e11, 1.25470588928e11, 6.3161765888e10, 8.39558784e8, 1.73088227328e11, 1.61617641472e11, 1.62500001792e11, 1.55294121984e11, 1.502941184e11, 1.51176462336e11, 1.51029415936e11, 1.49999992832e11, 1.54999996416e11, 1.56470575104e11, 1.5720587264e11, 1.63676471296e11, 1.62352939008e11, 1.64264706048e11, 1.64264706048e11, 1.71176460288e11, 1.7852940288e11, 1.79999997952e11, 1.85588219904e11, 1.88382347264e11, 1.87794112512e11, 1.90882349056e11, 1.86029408256e11, 1.95147055104e11, 1.97352931328e11, 1.988235264e11, 1.97499994112e11, 1.939705856e11, 1.88529410048e11, 1.85147047936e11, 1.89558816768e11, 1.89852925952e11, 1.9294117888e11, 1.91617646592e11]
t = [6.791390744557552e8, 7.070120692276629e8, 7.357080095340183e8, 7.650547154724817e8, 7.953377732904905e8, 8.262892758848644e8, 8.581056913126638e8, 8.907024681774093e8, 9.240880453929646e8, 9.582710918790629e8, 9.933604622496704e8, 1.0292664997565169e9, 1.0659972153375142e9, 1.1036653581333e9, 1.1421769036507227e9, 1.1815402286848478e9, 1.2218708563315039e9, 1.2630712844898963e9, 1.3051492865673156e9, 1.3482235382047653e9, 1.392193054974913e9, 1.4371785756406274e9, 1.483076055835938e9, 1.5300085878965065e9, 1.577753180029025e9, 1.6266666941311235e9, 1.67652468498346e9, 1.7273338946409273e9, 1.7793429703532004e9, 1.832197841268106e9, 1.8862716833809853e9, 1.941203362409068e9, 1.9973719124117074e9, 2.0545358728689203e9, 2.1128282306452894e9, 2.172257374393114e9, 2.232701288775207e9, 2.2944260629433947e9, 2.3571786931112576e9, 2.4210956101005635e9, 2.486183963119266e9, 2.552450182964812e9, 2.619900360140457e9, 2.6885398233809443e9, 2.7583743481169596e9, 2.8294089289359417e9, 2.9016477520188007e9, 2.9752368116074886e9, 3.050040012590594e9, 3.1262043907104836e9, 3.203590976156871e9, 3.2822025766905494e9, 3.362187185824641e9, 3.4435480641066747e9, 3.526142206529048e9, 3.610117379714123e9, 3.69547685841344e9, 3.782221971308321e9, 3.8703542985865817e9, 3.960025499246157e9, 4.0509329159676304e9, 4.1433801455385375e9, 4.2372134827372823e9, 4.332585745245504e9, 4.42949557800905e9, 4.527785588847821e9, 4.6276079215446825e9, 4.728959151607614e9, 4.831992579775848e9, 4.936388371718357e9, 5.042615972359425e9, 5.150351540426328e9, 5.259587906300355e9, 5.370637893543748e9, 5.483332574250255e9, 5.597499874197149e9, 5.713616678824965e9, 5.831346213258126e9, 5.950839544722556e9, 6.072083592751027e9, 6.195228369734235e9, 6.320094512101202e9, 6.4468300027655115e9, 6.57525118304769e9, 6.705670315341376e9, 6.838067740318667e9, 6.972421225110228e9, 7.1085430555991955e9, 7.246738559162813e9, 7.387151092833175e9, 7.529418333374686e9, 7.67367922760088e9, 7.820068139296936e9, 7.9687175061451025e9, 8.119428933534547e9, 8.272495645168805e9, 8.42754891778001e9, 8.585044839050801e9, 8.744774067776436e9, 8.907022198767035e9, 9.071411202306694e9, 9.238383393765379e9, 9.407723464781567e9, 9.57953881837197e9, 9.75409646093819e9, 9.931008306812086e9, 1.0110696445607868e10, 1.0293092516779022e10, 1.0478283115615255e10, 1.0666035004716991e10, 1.0856905143484087e10, 1.1050491978401829e10, 1.1247181325785295e10, 1.1446879325484026e10, 1.1649489873032072e10, 1.1855532096420149e10, 1.2064586801248566e10, 1.2277154396736849e10, 1.2492963249786226e10, 1.2712190677773657e10, 1.2935005054798855e10, 1.3161415803527374e10, 1.3391571393923643e10, 1.3625464261400404e10, 1.3863368101695465e10]

A = AkimaInterpolation(u, t)
plot(A; label = "AkimaInterpolation", xlims = [7.5e9, 7.55e9], ylims = [-1e9, 1e10])

A = PCHIPInterpolation(u, t)
plot!(A; label = "PCHIPInterpolation")
```

![fig](https://github.com/user-attachments/assets/8857a7fe-ace9-464a-bb77-60646031907c)

So `PCHIPInterpolation` does what you want, hopefully it will be merged and released soon.
