### ISSUE TITLE
Issues with linear interpolation and extrapolation

### ISSUE THREAD

**Issue by Leebre** [SciML/DataInterpolations.jl#293]
There seem to be problems with linear interpolation and also extrapolation. I will provide an MWE and sample data file.

If you run the MWE, the plot it produces looks something like this (for me, at least):

![Interpolation_issue](https://github.com/SciML/DataInterpolations.jl/assets/49341316/e7d5d4b2-a764-427d-a492-3e0842f4a262)

The blue line is the raw data and the red line is the linear interpolation. There seems to be a significant discrepancy in one particular region, where the interpolation is not following the data. I have no idea why, but this seems wrong. Perhaps it is linked to the very rapid drop-off (however, I would expect a linear interpolation to be able to handle it).

In addition, the extrapolation behavior does not seem to be working as expected. The data here (after padding) goes up to a maximum x-value of 8.2e8. In the MWE, I am requesting an interpolated value for x = 1e9. I believe this should throw an error; however, it seems to do the extrapolation anyway.

It's possible I am doing something wrong on my end, but if so I am not sure what ...

[Interpolation_issue.zip](https://github.com/user-attachments/files/16181799/Interpolation_issue.zip)

**Comment by SouthEndMusic** [comment]
`LinearInterpolation` gives plain linear interpolation, no smoothing. The extrapolation is a continuation of the first or last line segment.

Regarding the differences between the plots: note that the plotting library does linear interpolation within this log-log coordinate system, but `LinearInterpolation` does linear interpolation in the original coordinates.  Straight lines in these two coordinate systems are not the same.

Regarding extrapolation: the interpolation is not actually evaluated at 1e9. This is because for ranges `start:step:stop`, if `stop` is not an integer multiple of `step` away from `start`, it is not included

**Comment by Leebre** [comment]
@SouthEndMusic  thanks for your reply. That makes sense regarding the difference between log and regular coordinate systems for the interpolation and the plotting. I hadn't considered that!

Regarding the extrapolation question, however, if you look at my example, `grid1` , which the interpolation is being called on _does_ include 1e9 at the end of the vector - I have checked that. `grid1` is being created with the following:

```
grid1 = [collect(-3:0.04:3);6;9];   # log10 scale
grid1 = 10 .^grid1;
```

and then the interpolation:

```
interp1 = LinearInterpolation(data1_mod[:,2],data1_mod[:,1];extrapolate=false);
data1_interp = interp1((grid1))
```

so, the last entry of my `grid1` is clearly 1e9 here (which is outside of the interpolation data range)?

**Comment by SouthEndMusic** [comment]
Hi @Leebre, thanks for your reply. Interestingly, if you compute `data1_interp` with broadcasting, i.e. 
```julia
data1_interp = interp1.(grid)
```

you do get the appropriate error
```
ERROR: Cannot extrapolate as `extrapolate` keyword passed was `false`
```

I think I have identified where this bug originates in the code.

**Comment by Leebre** [comment]
@SouthEndMusic  ok, great. Thanks for finding the bug and posting the PR!
