### ISSUE TITLE
Remove `ReadOnlyArray` from type parameters

### ISSUE THREAD

**Issue by SouthEndMusic** [SciML/DataInterpolations.jl#301]
I want to hardcode the concrete type of an interpolation object as a field of a struct. In my opinion it shouldn't be required to have `ReadOnlyArrays` as an explicit dependency of my package to do this. I start to like this wrapper less and less 🙃 

Maybe a good way forward is to get rid of this wrapper, make caching parameters opt-in and properly document that if you do this you should not update `u, t`. This has the advantage that the default setting is more compatible with AD packages. Then we should only make sure that AD packages do not try to differentiate w.r.t. cached parameters.

**Comment by ChrisRackauckas** [comment]
That sounds reasonable. Indeed array wrappers always tend to introduce other problems. I think one other I saw was GPU support.
