### ISSUE TITLE
Extrapolation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DataInterpolations.jl#31]
Right now this library just errors if the time is before or beyond `A.t`. We should extend this to have a flag for allowing extrapolation (default true?), and then add the extrapolation for each method.

**Comment by sipah00** [comment]
which method to use for extrapolation for each data interpolation method, it would be great if you post some standard resource for it.

**Comment by ChrisRackauckas** [comment]
There really isn't a standard method. Just use the polynomial at the end and use its extension.

**Comment by PaulSoderlind** [comment]
https://github.com/kbarbary/Dierckx.jl has `bc = one of  ("nearest", "zero", "extrapolate", "error") `. I often find myself using "nearest."

**Comment by henry2004y** [comment]
Do we have the option of selecting extrapolation method like "nearest" now? It appears that the default is polynomial.

**Comment by ChrisRackauckas** [comment]
No extrapolation choices yet. In some cases extrapolation works with some default, but we need to extend it with options.

**Comment by TS-CUBED** [comment]
It would also be great to get an option to have a "periodic" option, which is part of the "extrapolation" options in some other packages (SciPy).

At the moment I use the work-around of wrapping the DataInterpolation into a function that calls the interpolator with the argument `t % tmax`. But that leads to a discontinuity at t=0.

**Comment by andreasnoack** [comment]
With https://github.com/PumasAI/DataInterpolations.jl/pull/92, I think most interpolations no longer throw when extrapolating.

**Comment by ChrisRackauckas** [comment]
Handled in https://github.com/SciML/DataInterpolations.jl/pull/184
