### ISSUE TITLE
Indicate output dimensionality in `AbstractInterpolation` type

### ISSUE THREAD

**Issue by adrhill** [SciML/DataInterpolations.jl#328]
As a developer writing a package extension for DataInterpolations.jl (https://github.com/adrhill/SparseConnectivityTracer.jl/pull/178), it would be useful if all `AbstractInterpolation`s indicated their output dimensionality, e.g.

```Julia
abstract type AbstractInterpolation{T,N} end 
```

or `{N,T}` instead of just `{T}`:

https://github.com/SciML/DataInterpolations.jl/blob/536cb0243038af495656ab11a219724acd56a293/src/DataInterpolations.jl#L5

**Comment by ChrisRackauckas** [comment]
That's probably fine.

**Comment by sathvikbhagavan** [comment]
Yeah, that can be done. Will work on it soon.
