### ISSUE TITLE
Configurable extrapolation behavior

### ISSUE THREAD

**Issue by SouthEndMusic** [SciML/DataInterpolations.jl#355]
I'm interested in making interpolation types configurable in my application, where extrapolation behavior is important. Up to now we have only used `LinearInterpolation`, where the extrapolation is easy to understand and well behaved. This is however not the case for interpolation types that use a high order polynomial in the boundary intervals, which are continued outside the data-defined domain for extrapolation. 

So, I would like to have several extrapolation options in stead of the current boolean:
1. No extrapolation allowed
2. The current extrapolation for maximum smoothness
3. Linear
4. Constant?

Would you consider this to be a good feature for `DataInterpolations`, or should I make a custom wrapper for my application?

**Comment by sathvikbhagavan** [comment]
I think it would be good to add those extrapolation methods here.

**Comment by SouthEndMusic** [comment]
Should the constructors keep the `extrapolate` keyword or can it be replaced by `extrapolation_type::Symbol` which has one of the above supported types (preferably also split in `upper_extrapolation_type` and `lower_extrapolation_type`)?
