### ISSUE TITLE
Spikes with closely spaced Loess interpolation

### ISSUE THREAD

**Issue by asinghvi17** [SciML/DataInterpolations.jl#36]
<img width="548" alt="Screen Shot 2019-08-10 at 2 17 07  10500PM" src="https://user-images.githubusercontent.com/32143268/62821881-ca4dd680-bb99-11e9-8cc7-381c10d54ccf.png">
The orange line is a LOESS fit with 10000 sampling points; the green one has 60.

**Comment by ChrisRackauckas** [comment]
LOESS was removed.
