### ISSUE TITLE
docstrings

### ISSUE THREAD

**Issue by jjstickel** [SciML/DataInterpolations.jl#98]
I would find it helpful for there to be docstrings for types and/or constructors.

**Comment by jjstickel** [comment]
Aside:  where is best for general discussion and questions about this package? Within issues? On discourse? I have a question about the `FT` specification of the interpolation types. What is it for? As far as I can tell, `t` is included in the indexing of the object when `FT == true`, but I don't see any other feature difference when `FT != true`.

**Comment by ChrisRackauckas** [comment]
@sathvikbhagavan do you think you can get around to this?

**Comment by sathvikbhagavan** [comment]
Yeah, I will add the docstrings

**Comment by alecloudenback** [comment]
Also, docstrings for the new extrapolations. Arguments and behavior beyond the interpolated range (e.g. constant value, constant slope, etc)
